FROM rust:1.90.0-bullseye

LABEL authors="heige"

# 设置环境变量
ENV LANG=C.UTF-8

# 设置nodejs和go版本
ENV NODEJS_VERSION=22 \
    GO_VERSION=1.24.11 \
    GOPATH=/go \
    GOROOT=/usr/local/go \
    CGO_ENABLED=0 \
    GOPROXY=https://goproxy.cn,direct \
    RUSTUP_DIST_SERVER=https://mirrors.ustc.edu.cn/rust-static \
    RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup \
    PATH=$PATH:/go/bin:/usr/local/go/bin

# 设置deb镜像源，这里我使用aliyun的镜像
RUN echo "deb http://mirrors.aliyun.com/debian bullseye main" > /etc/apt/sources.list &&  \
    echo "deb http://mirrors.aliyun.com/debian-security bullseye-security main" >> /etc/apt/sources.list &&  \
    echo "deb http://mirrors.aliyun.com/debian bullseye-updates main" >> /etc/apt/sources.list &&  \
    apt-get update && apt-get install -y ca-certificates gcc cmake make libtool vim bash curl libc6-dev wget  \
    git net-tools protobuf-compiler apt-transport-https python3-dev python3-pip build-essential  \
    libcurl4-openssl-dev libssl-dev libsasl2-dev libzstd-dev zlib1g-dev pkg-config && update-ca-certificates &&  \
    echo "[source.crates-io]" >> /usr/local/cargo/config.toml &&  \
    echo "replace-with = 'ustc'" >> /usr/local/cargo/config.toml &&  \
    echo "[source.ustc]" >> /usr/local/cargo/config.toml &&  \
    echo "registry = \"sparse+https://mirrors.ustc.edu.cn/crates.io-index/\"" >> /usr/local/cargo/config.toml &&  \
    echo "[net]" >> /usr/local/cargo/config.toml &&  \
    echo "git-fetch-with-cli=true" >> /usr/local/cargo/config.toml &&  \
    echo "[http]" >> /usr/local/cargo/config.toml &&  \
    echo "check-revoke = false" >> /usr/local/cargo/config.toml && \
    curl -fsSL https://deb.nodesource.com/setup_$NODEJS_VERSION.x -o nodesource_setup.sh && \
    chmod +x ./nodesource_setup.sh && \
    ./nodesource_setup.sh && apt-get install nodejs -y && \
    cd /usr/local && wget https://golang.google.cn/dl/go$GO_VERSION.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go$GO_VERSION.linux-amd64.tar.gz && \
    mkdir -p /go/bin && mkdir -p /go/pkg && mkdir -p /go/src && \
    ln -s /usr/local/go/bin/go /usr/bin/go &&  \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# 安装rdkafka
RUN cd /opt && wget https://github.com/confluentinc/librdkafka/archive/refs/tags/v2.12.1.tar.gz && \
    tar -zxf v2.12.1.tar.gz && cd /opt/librdkafka-2.12.1 && mkdir build && cd build && cmake .. && \
    make && make install

# 设置环境变量
ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
ENV PKG_CONFIG_ALLOW_SYSTEM_LIBS=1
ENV PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1

# 验证rdkafka是否安装
RUN pkg-config --modversion rdkafka

# 设置默认命令
CMD ["bash"]
